@UrlShortener.TokenRangeService_HostAddress = https://api-rixxremzmcmyw.azurewebsites.net

//
// Home page to return 'Hello world!'
//
GET {{UrlShortener.TokenRangeService_HostAddress}}/
Accept: application/json

###
