global using Xunit;
global using Microsoft.AspNetCore.Mvc.Testing;
global using System.Net.Http.Json;
global using System.Net;
global using FluentAssertions;
global using UrlShortener.Api.Core;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.TestHost;
global using Microsoft.Extensions.DependencyInjection;