name: Azure Deploy

on: 
 push: 
  branches:
   - main
  paths:
    - Azure.Infrastructure/**
 pull_request:
  branches:
    - main
  paths:
    - Azure.Infrastructure/**
 workflow_dispatch: # manual trigger

permissions:
  id-token: write
  contents: read

jobs:
 deploy-dev:
  runs-on: ubuntu-latest
  environment: Development
  steps:
    - uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_APP_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - uses: Azure/CLI@v2
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
          echo "Azure resource group created"

    - name: Deploy  
      uses: azure/arm-deploy@v2
      with:
        resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
        template: ./Azure.Infrastructure/main.bicep
        parameters: pgSqlPassword=${{ secrets.PG_SQL_PASSWORD }}

  # deploy-stg:
  #   runs-on: ubuntu-latest
  #   needs: deploy-dev
  #   environment: Staging
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Azure login
  #       uses: azure/login@v2.1.1
  #       with:
  #         client-id: ${{secrets.AZURE_APP_ID}}
  #         tenant-id: ${{secrets.AZURE_TENANT_ID}}
  #         subscription-id: ${{vars.AZURE_SUBSCRIPTION_ID}}

  #     - uses: Azure/CLI@v2
  #       with:
  #         inlineScript:
  #           #!/bin/bash
  #           echo "\n Azure resource group creation for ** Staging ** \n"
  #           az group create --name ${{vars.RESOURCE_GROUP_NAME}} --location ${{vars.RESOURCE_GROUP_LOCATION}}
  #           echo "\n Azure resource group for ** Staging ** created \n"

  #     - name: Deploy
  #       uses: azure/arm-deploy@v2
  #       with:
  #         resourceGroupName: ${{vars.RESOURCE_GROUP_NAME}}
  #         template: ./Infrastructure/main.bicep

  # deploy-prd:
  #   runs-on: ubuntu-latest
  #   needs: deploy-stg
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   environment: Production
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Azure login
  #       uses: azure/login@v2.1.1
  #       with:
  #         client-id: ${{secrets.AZURE_APP_ID}}
  #         tenant-id: ${{secrets.AZURE_TENANT_ID}}
  #         subscription-id: ${{vars.AZURE_SUBSCRIPTION_ID}}

  #     - uses: Azure/CLI@v2
  #       with:
  #         inlineScript:
  #           #!/bin/bash
  #           echo "Azure resource group creation"
  #           az group create --name ${{vars.RESOURCE_GROUP_NAME}} --location ${{vars.RESOURCE_GROUP_LOCATION}}
  #           echo "Azure resource group for ** Production ** created"

  #     - name: Deploy
  #       uses: azure/arm-deploy@v2
  #       with:
  #         resourceGroupName: ${{vars.RESOURCE_GROUP_NAME}}
  #         template: ./Infrastructure/main.bicep
