# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Token range

on:
  push:
    branches: [ "main" ]
    paths:
      - UrlShortener.TokenRangeService/**
  pull_request:
    branches: [ "main" ]
    paths:
      - UrlShortener.TokenRangeService/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ./UrlShortener.TokenRangeService/ --no-restore

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: dotnet publish
      run: dotnet publish ./UrlShortener.TokenRangeService/ -c Release -o ${{env.DOTNET_ROOT}}/tokenrangeapp

    - name: upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/tokenrangeapp

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: Development

    steps:
      - name: Download artefact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{vars.TOKENRANGE_RESOURCE_NAME}}
          slot-name: 'Production'
          publish-profile: ${{secrets.AZURE_TOKENRANGE_PUBLISH_PROFILE}}
          package: .
